server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  data:
    mongodb:
      uri: mongodb+srv://user:dsdPassword@cluster0.e1yles2.mongodb.net/?retryWrites=true&w=majority
      database: TriggerMock